### ISSUE TITLE
Autocomplete is always "Color Picker" since v10

### ISSUE THREAD

**Issue by elliottmangham** [widersky/postcss-nova-plugin#2]
Hey,

Ever since Nova updated to v10 the PostCSS syntax is very aggressive with the autocomplete, as it is always "Color Picker". This makes it hard to use the autocomplete tool, snippets and such.

Here are some examples:

Example 1:
<img width="311" alt="Shared Upload (2022-11-04 at 3 41 03)@2x" src="https://user-images.githubusercontent.com/12933804/200017747-425a1057-d8ad-4436-8378-3906dc047e49.png">

Example 2:
<img width="262" alt="Shared Upload (2022-11-04 at 3 44 37)@2x" src="https://user-images.githubusercontent.com/12933804/200017793-8dd9f896-041c-4b8b-af95-0755c86b0ff8.png">

Please help, thank you!

**Comment by widersky** [comment]
AFAIK it's a known issue with Nova itself - might work better in 10.1. Could you please verify? 🙏🏻 @elliottmangham

**Comment by elliottmangham** [comment]
Hey, I'm afraid that I get the same issue in the latest version

**Comment by widersky** [comment]
I'll check it then, thank you!

**Comment by widersky** [comment]
Fixed in 1.0.0 release
