### ISSUE TITLE
Repeating auto-complete options when enabled

### ISSUE THREAD

**Issue by elliottmangham** [widersky/postcss-nova-plugin#4]
Hey,

When PostCSS Nova plugin is enabled, the auto-complete options are duplicated:
![Shared Upload (2022-11-29 at 10 56 08)](https://user-images.githubusercontent.com/12933804/204511594-19110840-4197-4b2e-a9a2-051d7989fa07.png)

When disabled, you can see the options are no longer duplicated:
![Shared Upload (2022-11-29 at 10 55 57)](https://user-images.githubusercontent.com/12933804/204511543-a2293def-d18d-4155-a4f2-692ccf445c00.png)

Nova: 10.3
Plugin: 1.0.0

Thanks so much!

**Comment by widersky** [comment]
@elliottmangham It can be hard to debug, because in development mode everything works flawlessly, but I certainly won't leave it that way :)

**Comment by widersky** [comment]
Fixed in 1.1.0. Should be available to download soon :)
