### ISSUE TITLE
Pasting into PostCSS syntax crashes Nova

### ISSUE THREAD

**Issue by elliottmangham** [widersky/postcss-nova-plugin#5]
Hello!

Note: I have reported the following issue to the Nova development team, however, the issue is currently exclusive to this plugin according to my tests.

**Screen recording:**
https://cloud.coderesolution.com/WgJwnyk6

**Description:**
When a paste into a file with PostCSS syntax set, it crashes Nova and exits the app. If I paste on any other syntax, it works. This has been happening since Nova v11.1 released 1st June 2023.

**Mac:**
Chip: Apple M1 Max
Memory: 32 GB
MacOS: Ventura 13.4 (22F66)

**Nova:**
v11.1

Thank you!

**Comment by widersky** [comment]
Hi @elliottmangham ! I can't reproduce this issue, are you using other Nova plugins? Have you tried to disable every other plugin and check again?

**Comment by elliottmangham** [comment]
Hey, appreciate the response!

I have since been testing this further and it appears to happen in other syntaxes as well. Bizarrely, all-of-a-sudden, any syntax has the issue, whereas before it was exclusively this plugin.

I guess this means that it is down to Nova to fix, I just hope it isn't just me!
